import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";

/**
 * Geist Sans font configuration.
 */
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

/**
 * Geist Mono font configuration.
 */
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

/**
 * Application metadata.
 */
export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
