import type { OptionsConfig } from "@antfu/eslint-config";

const config: OptionsConfig["react"] = {
  overrides: {
    "react-dom/no-dangerously-set-innerhtml": "error",
    "react-dom/no-missing-button-type": "off",
    "react-dom/no-missing-iframe-sandbox": "error",
    "react-dom/no-script-url": "error",
    "react-dom/no-unsafe-iframe-sandbox": "error",
    "react-dom/no-unsafe-target-blank": "error",
    "react-hooks-extra/no-direct-set-state-in-use-effect": "error",
    "react-hooks-extra/no-unnecessary-use-prefix": "error",
    "react-hooks-extra/prefer-use-state-lazy-initialization": "error",
    "react-hooks/exhaustive-deps": "error",
    "react-refresh/only-export-components": "off",
    "react-web-api/no-leaked-event-listener": "error",
    "react-web-api/no-leaked-interval": "error",
    "react-web-api/no-leaked-resize-observer": "error",
    "react-web-api/no-leaked-timeout": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-uses-vars": "error",
    "react/no-array-index-key": "error",
    "react/no-children-count": "error",
    "react/no-children-for-each": "error",
    "react/no-children-map": "error",
    "react/no-children-only": "error",
    "react/no-children-to-array": "error",
    "react/no-clone-element": "error",
    "react/no-comment-textnodes": "error",
    "react/no-context-provider": "error",
    "react/no-duplicate-key": "error",
    "react/no-forward-ref": "error",
    "react/no-implicit-key": "error",
    "react/no-set-state-in-component-did-mount": "error",
    "react/no-set-state-in-component-did-update": "error",
    "react/no-set-state-in-component-will-update": "error",
    "react/no-unsafe-component-will-mount": "error",
    "react/no-unsafe-component-will-receive-props": "error",
    "react/no-unsafe-component-will-update": "error",
    "react/no-unstable-context-value": "error",
    "react/no-unstable-default-props": "error",
    "react/no-unused-class-component-members": "error",
    "react/no-unused-state": "error",
    "react/no-use-context": "error",
    "react/no-useless-forward-ref": "error",
  },
};

export default config;
